sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t eladbi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eladbi/docker-react npm run test -- --coverage