sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t eladbi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eladbi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-198815971655"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"